services:
  mongo:
    image: mongo:latest
    container_name: meu-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: wishlist_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  wishlist-api:
    build: .
    container_name: wishlist-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/wishlist_db
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - wishlist-api
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  mongo-data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge